name: build

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

  test:
    runs-on: ubuntu-latest
    container:
      image: python:2.7.18-slim
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - uses: actions/checkout@master
        with:
          path: app

      - run: pwd && cd app && ls && python -m unittest discover

